name: "Code quality workflow"

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions: read-all

concurrency:
  group: code_quality
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}
    working-directory: .

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  code_quality:
    name: "Code quality"
    runs-on: windows-latest
    steps:

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          echo "$CONDA\condabin" >> $GITHUB_PATH
          echo "$CONDA" >> $GITHUB_PATH
          echo "$CONDA\Scripts" >> $GITHUB_PATH
          echo $GITHUB_PATH
          echo $PATH
          conda init bash
          conda env update --file win_environment.yaml

      - uses: actions/cache@v2
        with:
          path: C:\Miniconda\envs\ml_snippets_service
          key: win-conda-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Test with pytest
        run: |
          conda info
          conda activate ml_snippets_service
          conda info
          conda env list
          python -m pytest --cov=src.main.app -s -v src/test/app/tests.py --cov-branch --junitxml coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}